---
title: "layouts"
format: html
---

::::: {.columns .column-page}
:::{.sidebar}
hello there good frriend!
:::
:::{.column-screen-right}
Quarto supports a variety of page layout options that enable you to author content that:

Fills the main content region
Overflows the content region
Spans the entire page
Occupies the document margin
Quarto uses the concept of columns to describe page layout (e.g. the “body” column, the “margin” column, etc.). Below we’ll describe how to arrange content into these columns.

All of the layout capabilities described in this document work for HTML output and many work for PDF and LaTeX output. For details about the PDF / LaTeX output, see PDF/LaTeX Layout.
Quarto supports a variety of page layout options that enable you to author content that:

Fills the main content region
Overflows the content region
Spans the entire page
Occupies the document margin
Quarto uses the concept of columns to describe page layout (e.g. the “body” column, the “margin” column, etc.). Below we’ll describe how to arrange content into these columns.

All of the layout capabilities described in this document work for HTML output and many work for PDF and LaTeX output. For details about the PDF / LaTeX output, see PDF/LaTeX Layout.
Quarto supports a variety of page layout options that enable you to author content that:

Fills the main content region
Overflows the content region
Spans the entire page
Occupies the document margin
Quarto uses the concept of columns to describe page layout (e.g. the “body” column, the “margin” column, etc.). Below we’ll describe how to arrange content into these columns.

All of the layout capabilities described in this document work for HTML output and many work for PDF and LaTeX output. For details about the PDF / LaTeX output, see PDF/LaTeX Layout.
Quarto supports a variety of page layout options that enable you to author content that:

Fills the main content region
Overflows the content region
Spans the entire page
Occupies the document margin
Quarto uses the concept of columns to describe page layout (e.g. the “body” column, the “margin” column, etc.). Below we’ll describe how to arrange content into these columns.

All of the layout capabilities described in this document work for HTML output and many work for PDF and LaTeX output. For details about the PDF / LaTeX output, see PDF/LaTeX Layout.
:::
:::

```{=html}
<style>
.sidebar {
  height: 100%; /* Full-height: remove this if you want "auto" height */
  width: 160px; /* Set the width of the sidebar */
  position: fixed; /* Fixed Sidebar (stay in place on scroll) */
  z-index: 1; /* Stay on top */
  top: 0; /* Stay at the top */
  left: 0;
  background-color: #111; /* Black */
  overflow-x: hidden; /* Disable horizontal scroll */
  padding-top: 20px;
}
.main {
  margin-left: 160px; /* Same as the width of the sidebar */
  padding: 0px 10px;
}
</style>
```

